# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    "accepts-1.3.5" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.5.tgz";
        sha1 = "eb777df6011723a3b14e8a72c0805c8e86746bd2";
      };
    };
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha1 = "73b5eeca3fab653e3d3f9422b341ad42205dc965";
      };
    };
    "another-json-0.2.0" = {
      name = "another-json";
      packageName = "another-json";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/another-json/-/another-json-0.2.0.tgz";
        sha1 = "b5f4019c973b6dd5c6506a2d93469cb6d32aeedc";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "array-uniq-1.0.3" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.3.tgz";
        sha1 = "af6ac877a25cc7f74e058894753858dfdb24fdb6";
      };
    };
    "asn1-0.2.4" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.4.tgz";
        sha512 = "jxwzQpLQjSmWXgwaCZE9Nz+glAG01yF1QnWgbhGwHI5A6FRIEY6IVqtHhIepHqI7/kyEyQEagBC5mBEFlIYvdg==";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "async-0.2.10" = {
      name = "async";
      packageName = "async";
      version = "0.2.10";
      src = fetchurl {
        url = "http://registry.npmjs.org/async/-/async-0.2.10.tgz";
        sha1 = "b6bbe0b0674b9d719708ca38de8c237cb526c3d1";
      };
    };
    "async-1.0.0" = {
      name = "async";
      packageName = "async";
      version = "1.0.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/async/-/async-1.0.0.tgz";
        sha1 = "f8fc04ca3a13784ade9e1641af98578cfbd647a9";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.8.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.8.0.tgz";
        sha512 = "ReZxvNHIOv88FlT7rxcXIIC0fPt4KZqZbOlivyWtXLt8ESx84zd3kMC6iK5jVeS2qt+g7ftS7ye4fi06X5rtRQ==";
      };
    };
    "babel-runtime-6.26.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz";
        sha1 = "965c7058668e82b55d7bfe04ff2337bc8b5647fe";
      };
    };
    "base64-js-1.3.0" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.0.tgz";
        sha512 = "ccav/yGvoa80BQDljCxsmmQ3Xvx60/UpBIij5QN21W3wBi/hhIC9OoO+KLpu9IJTS9j4DRVJ3aDDF9cMSoa2lw==";
      };
    };
    "basic-auth-2.0.1" = {
      name = "basic-auth";
      packageName = "basic-auth";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/basic-auth/-/basic-auth-2.0.1.tgz";
        sha512 = "NF+epuEdnUYVlGuhaxbbq+dvJttwLnGY+YixlXlME5KpQ5W3CnXA5cVTneY3SPbPDRkcjMbifrwmFYcClgOZeg==";
      };
    };
    "bcrypt-pbkdf-1.0.2" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz";
        sha1 = "a4301d389b6a43f9b67ff3ca11a3f6637e360e9e";
      };
    };
    "binary-search-tree-0.2.5" = {
      name = "binary-search-tree";
      packageName = "binary-search-tree";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-search-tree/-/binary-search-tree-0.2.5.tgz";
        sha1 = "7dbb3b210fdca082450dad2334c304af39bdc784";
      };
    };
    "bintrees-1.0.1" = {
      name = "bintrees";
      packageName = "bintrees";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bintrees/-/bintrees-1.0.1.tgz";
        sha1 = "0e655c9b9c2435eaab68bf4027226d2b55a34524";
      };
    };
    "bluebird-2.11.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "2.11.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz";
        sha1 = "534b9033c022c9579c56ba3b3e5a5caafbb650e1";
      };
    };
    "bluebird-3.5.3" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.5.3.tgz";
        sha512 = "/qKPUQlaW1OyR51WeCPBvRnAlnZFUJkCSG5HzGnuIqhgyJtF+T94lFnn33eiazjRm2LAHVy2guNnaq48X9SJuw==";
      };
    };
    "body-parser-1.18.3" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.18.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.18.3.tgz";
        sha1 = "5b292198ffdd553b3a0f20ded0592b956955c8b4";
      };
    };
    "browser-request-0.3.3" = {
      name = "browser-request";
      packageName = "browser-request";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-request/-/browser-request-0.3.3.tgz";
        sha1 = "9ece5b5aca89a29932242e18bf933def9876cc17";
      };
    };
    "buffer-5.2.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.2.1.tgz";
        sha512 = "c+Ko0loDaFfuPWiL02ls9Xd3GO3cPVmUobQ6t3rXNUk304u6hGq+8N/kFi+QEIKhzK3uwolVhLzszmfLmMLnqg==";
      };
    };
    "bytes-3.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz";
        sha1 = "d32815404d689699f85a4ea4fa8755dd13a96048";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "chalk-2.4.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.1.tgz";
        sha512 = "ObN6h1v2fTJSmUXoS3nMQ92LbDK9be4TV+6G+omQlGJFdcUX5heKi1LZ1YnRMIgwTLEj3E24bT6tYni50rlCfQ==";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "http://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "colors-1.3.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.3.2.tgz";
        sha512 = "rhP0JSBGYvpcNQj4s5AdShMeE5ahMop96cTeDl/v9qQQm2fYClE2QXZRi8wLzc+GmXSxdIqqbOIAhyObEXDbfQ==";
      };
    };
    "combined-stream-1.0.7" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.7.tgz";
        sha512 = "brWl9y6vOB1xYPZcpZde3N9zDByXTosAeMDo4p1wzo6UMOX4vumB+TP1RZ76sfE6Md68Q0NJSrE/gbezd4Ul+w==";
      };
    };
    "content-disposition-0.5.2" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.2.tgz";
        sha1 = "0cf68bb9ddf5f2be7961c3a85178cb85dba78cb4";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "core-js-2.5.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.5.7.tgz";
        sha512 = "RszJCAxg/PP6uzXVXL6BsxSXx/B05oJAQ2vkJRjyjrEcNVycaqOmNb5OTxZPE3xa5gwZduqza6L9JOCenh/Ecw==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "crc-3.8.0" = {
      name = "crc";
      packageName = "crc";
      version = "3.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc/-/crc-3.8.0.tgz";
        sha512 = "iX3mfgcTMIq3ZKLIsVFAbv7+Mc10kxabAGQb8HvjA1o3T1PIYprbakQ65d3I+2HGHt6nSKkM9PYjgoJO2KcFBQ==";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "dom-serializer-0.1.0" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.1.0.tgz";
        sha1 = "073c697546ce0780ce23be4a28e293e40bc30c82";
      };
    };
    "domelementtype-1.1.3" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.1.3";
      src = fetchurl {
        url = "http://registry.npmjs.org/domelementtype/-/domelementtype-1.1.3.tgz";
        sha1 = "bd28773e2642881aec51544924299c5cd822185b";
      };
    };
    "domelementtype-1.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/domelementtype/-/domelementtype-1.3.0.tgz";
        sha1 = "b17aed82e8ab59e52dd9c19b1756e0fc187204c2";
      };
    };
    "domhandler-2.4.2" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.4.2.tgz";
        sha512 = "JiK04h0Ht5u/80fdLMCEmV4zkNh2BcoMFBmZ/91WtYZ8qVXSKjiw7fXMgFPnHcSZgOo3XdinHvmnDUeMf5R4wA==";
      };
    };
    "domutils-1.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.7.0.tgz";
        sha512 = "Lgd2XcJ/NjEw+7tFvfKxOzCYKZsdct5lczQ2ZaQY8Djz7pfAD3Gbp8ySJWtreII/vDlMVmxwa6pHmdxIYgttDg==";
      };
    };
    "ecc-jsbn-0.1.2" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.2.tgz";
        sha1 = "3a83a904e54353287874c564b7549386849a98c9";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "entities-1.1.2" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.2.tgz";
        sha512 = "f2LZMYl1Fzu7YSBKg+RoROelpOaNrcGmE9AZubeDfrCEia483oW4MI4VyFd5VNHIgQ/7qm1I0wUHK1eJnn2y2w==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha1 = "41ae2eeb65efa62268aebfea83ac7d79299b0887";
      };
    };
    "express-4.16.4" = {
      name = "express";
      packageName = "express";
      version = "4.16.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.16.4.tgz";
        sha512 = "j12Uuyb4FMrd/qQAm6uCHAkPtO8FDTRJZBDd5D2KOL2eLaz1yUNdUB/NOIyq0iU4q4cFarsUCrnFDPBcnksuOg==";
      };
    };
    "extend-2.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-2.0.2.tgz";
        sha512 = "AgFD4VU+lVLP6vjnlNfF7OeInLTyeyckCNPEsuxz1vi786UuK/nk6ynPuhn/h+Ju9++TQyr5EpLRI14fc1QtTQ==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "fast-deep-equal-1.1.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.1.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.1.0.tgz";
        sha1 = "c053477817c86b51daa853c81e059b733d023614";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "fast-safe-stringify-2.0.6" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.0.6.tgz";
        sha512 = "q8BZ89jjc+mz08rSxROs8VsrBBcn1SIw1kq9NjolL509tkABRk9io01RAjSaEv1Xb2uFLt8VtRiZbGp5H8iDtg==";
      };
    };
    "fecha-2.3.3" = {
      name = "fecha";
      packageName = "fecha";
      version = "2.3.3";
      src = fetchurl {
        url = "http://registry.npmjs.org/fecha/-/fecha-2.3.3.tgz";
        sha512 = "lUGBnIamTAwk4znq5BcqsDaxSmZ9nDVJaij6NvRt/Tg4R69gERA+otPKbS86ROw9nxVMw2/mp1fnaiWqbs6Sdg==";
      };
    };
    "file-stream-rotator-0.4.1" = {
      name = "file-stream-rotator";
      packageName = "file-stream-rotator";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-stream-rotator/-/file-stream-rotator-0.4.1.tgz";
        sha512 = "W3aa3QJEc8BS2MmdVpQiYLKHj3ijpto1gMDlsgCRSKfIUe6MwkcpODGPQ3vZfb0XvCeCqlu9CBQTN7oQri2TZQ==";
      };
    };
    "finalhandler-1.1.1" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.1.1";
      src = fetchurl {
        url = "http://registry.npmjs.org/finalhandler/-/finalhandler-1.1.1.tgz";
        sha512 = "Y1GUDo39ez4aHAw7MysnUD5JzYX+WaIj8I57kO3aEPT1fFRL4sr7mjei97FgnwhAyyzRYmQZaTHb2+9uZ1dPtg==";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.3" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.3.tgz";
        sha512 = "1lLKB2Mu3aGP1Q/2eCOx0fNbRMe7XdwktwOruhfqqd0rIJWwN4Dh+E3hrPSlDCXnSR7UtZ1N38rVXm+6+MEhJQ==";
      };
    };
    "forwarded-0.1.2" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.2.tgz";
        sha1 = "98c23dab1175657b8c0573e8ceccd91b0ff18c84";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha1 = "3d8cadd90d976569fa835ab1f8e4b23a105605a7";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.1.0" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.1.0.tgz";
        sha512 = "+qnmNjI4OfH2ipQ9VQOw23bBd/ibtfbVdK2fYbY4acTDqKTW/YDp9McimZdDbG8iV9fZizUqQMD5xvriB146TA==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "htmlparser2-3.10.0" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.10.0.tgz";
        sha512 = "J1nEUGv+MkXS0weHNWVKJJ+UrLfePxRWpN3C9bEi9fLxL2+ggW94DQvgYVXsaT30PGwYRIZKNZXuyMhp3Di4bQ==";
      };
    };
    "http-errors-1.6.3" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.3";
      src = fetchurl {
        url = "http://registry.npmjs.org/http-errors/-/http-errors-1.6.3.tgz";
        sha1 = "8b55680bb4be283a0b5bf4ea2e38580be1d9320d";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "iconv-lite-0.4.23" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.23.tgz";
        sha512 = "neyTUVFtahjf0mB3dZT77u+8O0QB89jFdnBkd5P1JgYPbPaia3gXXOVL2fq8VyU2gMMD7SaN7QukTB/pmXYvDA==";
      };
    };
    "ieee754-1.1.12" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.12.tgz";
        sha512 = "GguP+DRY+pJ3soyIiGPTvdiVXjZ+DbXOxGpXn3eMvNW4x4irjqXm4wHKscC+TfxSJ0yw/S1F24tqdMNsMZTiLA==";
      };
    };
    "immediate-3.0.6" = {
      name = "immediate";
      packageName = "immediate";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/immediate/-/immediate-3.0.6.tgz";
        sha1 = "9db1dbd0faf8de6fbe0f5dd5e56bb606280de69b";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "ipaddr.js-1.8.0" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.8.0.tgz";
        sha1 = "eaa33d6ddd7ace8f7f6fe0c9ca0440e706738b1e";
      };
    };
    "irc-colors-1.4.3" = {
      name = "irc-colors";
      packageName = "irc-colors";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/irc-colors/-/irc-colors-1.4.3.tgz";
        sha512 = "VeAnFC9fkb4nB/s6UtTNf3BH2wOk/sSBSzIzCpFwrgoFxVl6J5sov7FXXA0kmbk/mVAZQXfXAsQFjWnGPf4cRg==";
      };
    };
    "irc-git://github.com/matrix-org/node-irc#c9abb427bec5016d94a2abf3e058cc62de09ea5a" = {
      name = "irc";
      packageName = "irc";
      version = "0.3.12";
      src = fetchgit {
        url = "git://github.com/matrix-org/node-irc";
        rev = "c9abb427bec5016d94a2abf3e058cc62de09ea5a";
        sha256 = "c349f40307b38c1127c6a49c8137b2160e991431b497ed106e9e7b144bdd4362";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jayschema-0.3.2" = {
      name = "jayschema";
      packageName = "jayschema";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jayschema/-/jayschema-0.3.2.tgz";
        sha512 = "UHLk2ya7ItaLjmMVJWGE9b5t7jD3DZfmURdmz+rOVSiSYnrCtgcxvNXuQavcK7bhUBlXFmrXwRAPXkCMDxxANg==";
      };
    };
    "js-yaml-3.12.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.12.0.tgz";
        sha512 = "PIt2cnwmPfL4hKNwqeiuz4bKfnzHTBv6HyVgjahA6mPLwPDzjDWrplJBMjHUFxku/N3FlmrbyPclad+I+4mJ3A==";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "lie-3.1.1" = {
      name = "lie";
      packageName = "lie";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lie/-/lie-3.1.1.tgz";
        sha1 = "9a436b2cc7746ca59de7a41fa469b3efb76bd87e";
      };
    };
    "localforage-1.7.3" = {
      name = "localforage";
      packageName = "localforage";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/localforage/-/localforage-1.7.3.tgz";
        sha512 = "1TulyYfc4udS7ECSBT2vwJksWbkwwTX8BzeUIiq8Y07Riy7bDAAnxDaPU/tWyOVmQAcWJIEIFP9lPfBGqVoPgQ==";
      };
    };
    "lodash.clonedeep-4.5.0" = {
      name = "lodash.clonedeep";
      packageName = "lodash.clonedeep";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz";
        sha1 = "e23f3f9c4f8fbdde872529c1071857a086e5ccef";
      };
    };
    "lodash.escaperegexp-4.1.2" = {
      name = "lodash.escaperegexp";
      packageName = "lodash.escaperegexp";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.escaperegexp/-/lodash.escaperegexp-4.1.2.tgz";
        sha1 = "64762c48618082518ac3df4ccf5d5886dae20347";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "lodash.mergewith-4.6.1" = {
      name = "lodash.mergewith";
      packageName = "lodash.mergewith";
      version = "4.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.mergewith/-/lodash.mergewith-4.6.1.tgz";
        sha512 = "eWw5r+PYICtEBgrBE5hhlT6aAa75f411bgDz/ZL2KZqYV03USvucsxcHUIlGTDTECs1eunpI7HOV7U+WLDvNdQ==";
      };
    };
    "logform-1.10.0" = {
      name = "logform";
      packageName = "logform";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/logform/-/logform-1.10.0.tgz";
        sha512 = "em5ojIhU18fIMOw/333mD+ZLE2fis0EzXl1ZwHx4iQzmpQi6odNiY/t+ITNr33JZhT9/KEaH+UPIipr6a9EjWg==";
      };
    };
    "matrix-appservice-0.3.5" = {
      name = "matrix-appservice";
      packageName = "matrix-appservice";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-appservice/-/matrix-appservice-0.3.5.tgz";
        sha512 = "oQcxlpERcUj90QbGjV7t5Ly5/Aze/sUwB9ZrIt1UMFwuNT+CgEzA7cxLDHAiJkXfgoNzFvjVnKJ3203oIuLONQ==";
      };
    };
    "matrix-appservice-bridge-1.6.1" = {
      name = "matrix-appservice-bridge";
      packageName = "matrix-appservice-bridge";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-appservice-bridge/-/matrix-appservice-bridge-1.6.1.tgz";
        sha512 = "jYg3BF9iuGTexYjWGfOJsf1OC7k2ECgSONnHLL6hZR3q5Vr8nEy7aw2JG+4h6jjOQ8enx1VSur2+Nj5S35ybCA==";
      };
    };
    "matrix-js-sdk-0.10.9" = {
      name = "matrix-js-sdk";
      packageName = "matrix-js-sdk";
      version = "0.10.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-js-sdk/-/matrix-js-sdk-0.10.9.tgz";
        sha512 = "2d8dziVXh/jO48a+ju16Qn90QHgx3MLSK//Kx1GF/5jL80xrw1Pq4ijgcypt0ntG0vQ0ALfzQ27hse/KO6QVDw==";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "mime-1.4.1" = {
      name = "mime";
      packageName = "mime";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.4.1.tgz";
        sha512 = "KI1+qOZu5DcW6wayYHSzR/tXKCDC5Om4s1z2QJjDULzLcmf3DvzS7oluY4HCTrc+9FiKmWUgeNLg7W3uIQvxtQ==";
      };
    };
    "mime-db-1.37.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.37.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.37.0.tgz";
        sha512 = "R3C4db6bgQhlIhPU48fUtdVmKnflq+hRdad7IyKhtFj06VPNVdk2RhiYL3UjQIlso8L+YxAtFkobT0VK+S/ybg==";
      };
    };
    "mime-types-2.1.21" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.21.tgz";
        sha512 = "3iL6DbwpyLzjR3xHSFNFeb9Nz/M8WDkX33t1GFQnFOllWk8pOrh/LSrB5OXlnlW5P9LH73X6loW/eogc+F5lJg==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "http://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "http://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "moment-2.22.2" = {
      name = "moment";
      packageName = "moment";
      version = "2.22.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.22.2.tgz";
        sha1 = "3c257f9839fc0e93ff53149632239eb90783ff66";
      };
    };
    "morgan-1.9.1" = {
      name = "morgan";
      packageName = "morgan";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/morgan/-/morgan-1.9.1.tgz";
        sha512 = "HQStPIV4y3afTiCYVxirakhlCfGkI161c76kKFca7Fk1JusM//Qeo1ej2XaMniiNeaZklMVrh3vTtIzpzwbpmA==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.1" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
        sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
      };
    };
    "nedb-1.8.0" = {
      name = "nedb";
      packageName = "nedb";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nedb/-/nedb-1.8.0.tgz";
        sha1 = "0e3502cd82c004d5355a43c9e55577bd7bd91d88";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "oauth-sign-0.9.0" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.9.0.tgz";
        sha512 = "fexhUFFPTGV8ybAtSIGbV6gOkSv8UtRbDBnAyLQw4QPKkgNlsH2ByPGtMUqdWkos6YCRmAqViwgZrJc/mRDzZQ==";
      };
    };
    "object-hash-1.3.0" = {
      name = "object-hash";
      packageName = "object-hash";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-hash/-/object-hash-1.3.0.tgz";
        sha512 = "05KzQ70lSeGSrZJQXE5wNDiTkBJDlUT/myi6RX9dVIvz7a7Qh4oH93BQdiPMn27nldYvVQCKMUaM83AfizZlsQ==";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "on-headers-1.0.1" = {
      name = "on-headers";
      packageName = "on-headers";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-headers/-/on-headers-1.0.1.tgz";
        sha1 = "928f5d0f470d49342651ea6794b0857c100693f7";
      };
    };
    "parseurl-1.3.2" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz";
        sha1 = "fc289d4ed8993119460c156253262cdc8de65bf3";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "postcss-6.0.23" = {
      name = "postcss";
      packageName = "postcss";
      version = "6.0.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-6.0.23.tgz";
        sha512 = "soOk1h6J3VMTZtVeVpv15/Hpdl2cBLX3CAw4TAbkpTJiNPk9YP/zWcD1ND+xEtvyuuvKzbxliTOIyvkSeSJ6ag==";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
      };
    };
    "prom-client-11.1.3" = {
      name = "prom-client";
      packageName = "prom-client";
      version = "11.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prom-client/-/prom-client-11.1.3.tgz";
        sha512 = "vpEQ8NltXq+lrtOYvPEoX+kvN4FG3LrIfa0/eVE8sfePDIprhV/RY7EX8u14EN4KWNjO9O70b9mNLHglSt1rzQ==";
      };
    };
    "prom-client-6.3.0" = {
      name = "prom-client";
      packageName = "prom-client";
      version = "6.3.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/prom-client/-/prom-client-6.3.0.tgz";
        sha1 = "5826993809ac554156e168cb44f218777cd0d4de";
      };
    };
    "proxy-addr-2.0.4" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.4.tgz";
        sha512 = "5erio2h9jp5CHGwcybmxmVqHmnCBZeewlfJ0pex+UW7Qny7OOZXTtH56TGNyBizkgiOwhJtMKrVzDTeKcySZwA==";
      };
    };
    "psl-1.1.29" = {
      name = "psl";
      packageName = "psl";
      version = "1.1.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/psl/-/psl-1.1.29.tgz";
        sha512 = "AeUmQ0oLN02flVHXWh9sSJF7mcdFq0ppid/JkErufc3hGIV/AMa8Fo9VgDo/cT2jFdOWoFvHp90qqBH54W+gjQ==";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "N5ZAX4/LxJmF+7wN74pUD6qAh9/wnvdQcjq9TZjevvXzSUo7bfmw91saqMjzGS2xq91/odN2dW/WOl7qQHNDGA==";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "raw-body-2.3.3" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.3.3.tgz";
        sha512 = "9esiElv1BrZoI3rCDuOuKCBRbuApGGaDPQfjSflGxdy4oyzqghxu6klEkkVIvBje+FF0BX9coEv8KqW6X/7njw==";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "http://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "readable-stream-3.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.0.6.tgz";
        sha512 = "9E1oLoOWfhSXHGv6QlwXJim7uNzd9EVlWK+21tCU9Ju/kR0/p2AZYPz4qSchgO8PlLIH4FpZYfzwS+rEksZjIg==";
      };
    };
    "regenerator-runtime-0.11.1" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz";
        sha512 = "MguG95oij0fC3QV3URf4V2SDYGJhJnJGqvIIgdECeODCT98wSWDAJ94SSuVpYQUoTcGUIL6L4yNB7j1DFFHSBg==";
      };
    };
    "request-2.88.0" = {
      name = "request";
      packageName = "request";
      version = "2.88.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.88.0.tgz";
        sha512 = "NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E+lHDAJzu7kLAkDeY08z2/A0hg==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sanitize-html-1.19.1" = {
      name = "sanitize-html";
      packageName = "sanitize-html";
      version = "1.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanitize-html/-/sanitize-html-1.19.1.tgz";
        sha512 = "zNYr6FvBn4bZukr9x2uny6od/9YdjCLwF+FqxivqI0YOt/m9GIxfX+tWhm52tBAPUXiTTb4bJTGVagRz5b06bw==";
      };
    };
    "semver-5.6.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.6.0.tgz";
        sha512 = "RS9R6R35NYgQn++fkDWaOmqGoj4Ek9gGs+DPxNUZKuwE183xjJroKvyo1IzVFeXvUrvmALy6FWD5xrdJT25gMg==";
      };
    };
    "send-0.16.2" = {
      name = "send";
      packageName = "send";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.16.2.tgz";
        sha512 = "E64YFPUssFHEFBvpbbjr44NCLtI1AohxQ8ZSiJjQLskAdKuriYEP6VyGEsRDH8ScozGpkaX1BGvhanqCwkcEZw==";
      };
    };
    "serve-static-1.13.2" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.13.2.tgz";
        sha512 = "p/tdJrO4U387R9oMjb1oj7qSMaMfmOyd4j9hOFoxZe2baQszgHcSWjuya/CiT5kgZZKRudHNOA0pYXOl8rQ5nw==";
      };
    };
    "setprototypeof-1.1.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.0.tgz";
        sha512 = "BvE/TwpZX4FXExxOxZyRGQQv651MSwmWKZGqvmPcRIjDqWub67kTKuIMx43cZZrS/cBBzwBcNDWoFxt2XEFIpQ==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "srcset-1.0.0" = {
      name = "srcset";
      packageName = "srcset";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/srcset/-/srcset-1.0.0.tgz";
        sha1 = "a5669de12b42f3b1d5e83ed03c71046fc48f41ef";
      };
    };
    "sshpk-1.15.2" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.15.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.15.2.tgz";
        sha512 = "Ra/OXQtuh0/enyl4ETZAfTaeksa6BXks5ZcjpSUNrjBr0DvrJKX+1fsKDPpT9TBXgHAFsa4510aNVgI8g/+SzA==";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "statuses-1.4.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz";
        sha512 = "zhSCtt8v2NDrRlPQpCNtw/heZLtfUDqxBM1udqikb/Hbk52LK4nQSwr10u77iopCW5LsyHpuXS0GnEc48mLeew==";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha1 = "161c7dac177659fd9811f43771fa99381478628c";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "tdigest-0.1.1" = {
      name = "tdigest";
      packageName = "tdigest";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tdigest/-/tdigest-0.1.1.tgz";
        sha1 = "2e3cb2c39ea449e55d1e6cd91117accca4588021";
      };
    };
    "tough-cookie-2.4.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.4.3.tgz";
        sha512 = "Q5srk/4vDM54WJsJio3XNn6K2sCG+CQ8G5Wz6bZhRZoAe/+TxjWB/GlFAnYEbkYVlON9FMk/fE3h2RLpPXo4lQ==";
      };
    };
    "triple-beam-1.3.0" = {
      name = "triple-beam";
      packageName = "triple-beam";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/triple-beam/-/triple-beam-1.3.0.tgz";
        sha512 = "XrHUvV5HpdLmIj4uVMxHggLbFSZYIn7HEWsqePZcI50pco+MPqJ50wMGY794X7AOOhxOBAjbkqfAbEe/QMp2Lw==";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "type-is-1.6.16" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.16.tgz";
        sha512 = "HRkVv/5qY2G6I8iab9cI7v1bOIdhm94dVjQCPFElW9W+3GeDOSHmy2EBYe4VTApuzolPcmgFTN3ftVJRKR2J9Q==";
      };
    };
    "underscore-1.4.4" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz";
        sha1 = "61a6a32010622afa07963bf325203cf12239d604";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "util-extend-1.0.3" = {
      name = "util-extend";
      packageName = "util-extend";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-extend/-/util-extend-1.0.3.tgz";
        sha1 = "a7c216d267545169637b3b6edc6ca9119e2ff93f";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha1 = "9f95710f50a267947b2ccc124741c1028427e713";
      };
    };
    "uuid-3.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.2.tgz";
        sha512 = "yXJmeNaw3DnnKAOKJE51sL/ZaYfWJRl1pK9dr19YFCu0ObS231AB1/LbqTKRAQ5kw8A90rA6fr4riOUpTZvQZA==";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "when-3.4.6" = {
      name = "when";
      packageName = "when";
      version = "3.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/when/-/when-3.4.6.tgz";
        sha1 = "8fbcb7cc1439d2c3a68c431f1516e6dcce9ad28c";
      };
    };
    "winston-2.4.4" = {
      name = "winston";
      packageName = "winston";
      version = "2.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-2.4.4.tgz";
        sha512 = "NBo2Pepn4hK4V01UfcWcDlmiVTs7VTB1h7bgnB0rgP146bYhMxX0ypCz3lBOfNxCO4Zuek7yeT+y/zM1OfMw4Q==";
      };
    };
    "winston-compat-0.1.4" = {
      name = "winston-compat";
      packageName = "winston-compat";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-compat/-/winston-compat-0.1.4.tgz";
        sha512 = "mMEfFsSm6GmkFF+f4/0UJtG4N1vSaczGmXLVJYmS/+u2zUaIPcw2ZRuwUg2TvVBjswgiraN+vNnAG8z4fRUZ4w==";
      };
    };
    "winston-daily-rotate-file-3.5.1" = {
      name = "winston-daily-rotate-file";
      packageName = "winston-daily-rotate-file";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-daily-rotate-file/-/winston-daily-rotate-file-3.5.1.tgz";
        sha512 = "Y5CECbcJro55HWcWJSzI1DiQrbrfwwvKHdCCJn9wWsWCGfnCPDl5SWIokS2M0EvOKtbZUrlm5DPG522mvjdUBQ==";
      };
    };
    "winston-transport-4.2.0" = {
      name = "winston-transport";
      packageName = "winston-transport";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-transport/-/winston-transport-4.2.0.tgz";
        sha512 = "0R1bvFqxSlK/ZKTH86nymOuKv/cT1PQBMuDdA7k7f0S9fM44dNH6bXnuxwXPrN8lefJgtZq08BKdyZ0DZIy/rg==";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
  };
in
{
  "matrix-appservice-irc-0.11.2" = nodeEnv.buildNodePackage {
    name = "matrix-appservice-irc";
    packageName = "matrix-appservice-irc";
    version = "0.11.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/matrix-appservice-irc/-/matrix-appservice-irc-0.11.2.tgz";
      sha512 = "n4ah1bVDhWTv/HWTOk9gmm/ldBaojMflmUJokXYPQRq7MzKtEtJ9ZhnGhOKtAQIVg5SwsdGiJ8s/LOPzmCEoZQ==";
    };
    dependencies = [
      sources."abbrev-1.1.1"
      sources."accepts-1.3.5"
      sources."ajv-5.5.2"
      sources."another-json-0.2.0"
      sources."ansi-styles-3.2.1"
      sources."argparse-1.0.10"
      sources."array-flatten-1.1.1"
      sources."array-uniq-1.0.3"
      sources."asn1-0.2.4"
      sources."assert-plus-1.0.0"
      sources."async-0.2.10"
      sources."asynckit-0.4.0"
      sources."aws-sign2-0.7.0"
      sources."aws4-1.8.0"
      sources."babel-runtime-6.26.0"
      sources."base64-js-1.3.0"
      sources."basic-auth-2.0.1"
      sources."bcrypt-pbkdf-1.0.2"
      sources."binary-search-tree-0.2.5"
      sources."bintrees-1.0.1"
      sources."bluebird-3.5.3"
      sources."body-parser-1.18.3"
      sources."browser-request-0.3.3"
      sources."buffer-5.2.1"
      sources."bytes-3.0.0"
      sources."caseless-0.12.0"
      sources."chalk-2.4.1"
      sources."co-4.6.0"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."colors-1.0.3"
      sources."combined-stream-1.0.7"
      sources."content-disposition-0.5.2"
      sources."content-type-1.0.4"
      sources."cookie-0.3.1"
      sources."cookie-signature-1.0.6"
      sources."core-js-2.5.7"
      sources."core-util-is-1.0.2"
      sources."crc-3.8.0"
      sources."cycle-1.0.3"
      sources."dashdash-1.14.1"
      sources."debug-2.6.9"
      sources."delayed-stream-1.0.0"
      sources."depd-1.1.2"
      sources."destroy-1.0.4"
      (sources."dom-serializer-0.1.0" // {
        dependencies = [
          sources."domelementtype-1.1.3"
        ];
      })
      sources."domelementtype-1.3.0"
      sources."domhandler-2.4.2"
      sources."domutils-1.7.0"
      sources."ecc-jsbn-0.1.2"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."entities-1.1.2"
      sources."escape-html-1.0.3"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      sources."etag-1.8.1"
      (sources."express-4.16.4" // {
        dependencies = [
          sources."statuses-1.4.0"
        ];
      })
      sources."extend-2.0.2"
      sources."extsprintf-1.3.0"
      sources."eyes-0.1.8"
      sources."fast-deep-equal-1.1.0"
      sources."fast-json-stable-stringify-2.0.0"
      sources."fast-safe-stringify-2.0.6"
      sources."fecha-2.3.3"
      sources."file-stream-rotator-0.4.1"
      (sources."finalhandler-1.1.1" // {
        dependencies = [
          sources."statuses-1.4.0"
        ];
      })
      sources."forever-agent-0.6.1"
      sources."form-data-2.3.3"
      sources."forwarded-0.1.2"
      sources."fresh-0.5.2"
      sources."getpass-0.1.7"
      sources."har-schema-2.0.0"
      sources."har-validator-5.1.0"
      sources."has-flag-3.0.0"
      sources."htmlparser2-3.10.0"
      sources."http-errors-1.6.3"
      sources."http-signature-1.2.0"
      sources."iconv-lite-0.4.23"
      sources."ieee754-1.1.12"
      sources."immediate-3.0.6"
      sources."inherits-2.0.3"
      sources."ipaddr.js-1.8.0"
      sources."irc-git://github.com/matrix-org/node-irc#c9abb427bec5016d94a2abf3e058cc62de09ea5a"
      sources."irc-colors-1.4.3"
      sources."is-typedarray-1.0.0"
      sources."isarray-1.0.0"
      sources."isstream-0.1.2"
      sources."jayschema-0.3.2"
      sources."js-yaml-3.12.0"
      sources."jsbn-0.1.1"
      sources."json-schema-0.2.3"
      sources."json-schema-traverse-0.3.1"
      sources."json-stringify-safe-5.0.1"
      sources."jsprim-1.4.1"
      sources."lie-3.1.1"
      sources."localforage-1.7.3"
      sources."lodash.clonedeep-4.5.0"
      sources."lodash.escaperegexp-4.1.2"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.mergewith-4.6.1"
      (sources."logform-1.10.0" // {
        dependencies = [
          sources."colors-1.3.2"
          sources."ms-2.1.1"
        ];
      })
      sources."matrix-appservice-0.3.5"
      (sources."matrix-appservice-bridge-1.6.1" // {
        dependencies = [
          sources."bluebird-2.11.0"
          sources."extend-3.0.2"
          sources."prom-client-11.1.3"
        ];
      })
      sources."matrix-js-sdk-0.10.9"
      sources."media-typer-0.3.0"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      sources."mime-1.4.1"
      sources."mime-db-1.37.0"
      sources."mime-types-2.1.21"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."moment-2.22.2"
      sources."morgan-1.9.1"
      sources."ms-2.0.0"
      sources."nedb-1.8.0"
      sources."negotiator-0.6.1"
      sources."nopt-3.0.6"
      sources."number-is-nan-1.0.1"
      sources."oauth-sign-0.9.0"
      sources."object-hash-1.3.0"
      sources."on-finished-2.3.0"
      sources."on-headers-1.0.1"
      sources."parseurl-1.3.2"
      sources."path-to-regexp-0.1.7"
      sources."performance-now-2.1.0"
      sources."postcss-6.0.23"
      sources."process-nextick-args-2.0.0"
      sources."prom-client-6.3.0"
      sources."proxy-addr-2.0.4"
      sources."psl-1.1.29"
      sources."punycode-1.4.1"
      sources."qs-6.5.2"
      sources."range-parser-1.2.0"
      sources."raw-body-2.3.3"
      sources."readable-stream-3.0.6"
      sources."regenerator-runtime-0.11.1"
      (sources."request-2.88.0" // {
        dependencies = [
          sources."extend-3.0.2"
        ];
      })
      sources."safe-buffer-5.1.2"
      sources."safer-buffer-2.1.2"
      sources."sanitize-html-1.19.1"
      sources."semver-5.6.0"
      (sources."send-0.16.2" // {
        dependencies = [
          sources."statuses-1.4.0"
        ];
      })
      sources."serve-static-1.13.2"
      sources."setprototypeof-1.1.0"
      sources."source-map-0.6.1"
      sources."sprintf-js-1.0.3"
      sources."srcset-1.0.0"
      sources."sshpk-1.15.2"
      sources."stack-trace-0.0.10"
      sources."statuses-1.5.0"
      sources."string_decoder-1.1.1"
      sources."supports-color-5.5.0"
      sources."tdigest-0.1.1"
      sources."tough-cookie-2.4.3"
      sources."triple-beam-1.3.0"
      sources."tunnel-agent-0.6.0"
      sources."tweetnacl-0.14.5"
      sources."type-is-1.6.16"
      sources."underscore-1.4.4"
      sources."unpipe-1.0.0"
      sources."util-deprecate-1.0.2"
      sources."util-extend-1.0.3"
      sources."utils-merge-1.0.1"
      sources."uuid-3.3.2"
      sources."vary-1.1.2"
      sources."verror-1.10.0"
      sources."when-3.4.6"
      (sources."winston-2.4.4" // {
        dependencies = [
          sources."async-1.0.0"
        ];
      })
      sources."winston-compat-0.1.4"
      sources."winston-daily-rotate-file-3.5.1"
      (sources."winston-transport-4.2.0" // {
        dependencies = [
          sources."readable-stream-2.3.6"
        ];
      })
      sources."xtend-4.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An IRC Bridge for Matrix";
      homepage = "https://github.com/matrix-org/matrix-appservice-irc#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
  };
}