# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    "accepts-1.2.13" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.2.13.tgz";
        sha1 = "e5f1f3928c6d95fd96558c36ec3d9d0de4a6ecea";
      };
    };
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha1 = "73b5eeca3fab653e3d3f9422b341ad42205dc965";
      };
    };
    "another-json-0.2.0" = {
      name = "another-json";
      packageName = "another-json";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/another-json/-/another-json-0.2.0.tgz";
        sha1 = "b5f4019c973b6dd5c6506a2d93469cb6d32aeedc";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "array-uniq-1.0.3" = {
      name = "array-uniq";
      packageName = "array-uniq";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.3.tgz";
        sha1 = "af6ac877a25cc7f74e058894753858dfdb24fdb6";
      };
    };
    "asn1-0.1.11" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.1.11.tgz";
        sha1 = "559be18376d08a4ec4dbe80877d27818639b2df7";
      };
    };
    "asn1-0.2.4" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.4.tgz";
        sha512 = "jxwzQpLQjSmWXgwaCZE9Nz+glAG01yF1QnWgbhGwHI5A6FRIEY6IVqtHhIepHqI7/kyEyQEagBC5mBEFlIYvdg==";
      };
    };
    "assert-plus-0.1.5" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.1.5.tgz";
        sha1 = "ee74009413002d84cec7219c6ac811812e723160";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "async-0.2.10" = {
      name = "async";
      packageName = "async";
      version = "0.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.2.10.tgz";
        sha1 = "b6bbe0b0674b9d719708ca38de8c237cb526c3d1";
      };
    };
    "async-0.9.2" = {
      name = "async";
      packageName = "async";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.9.2.tgz";
        sha1 = "aea74d5e61c1f899613bf64bda66d4c78f2fd17d";
      };
    };
    "async-1.0.0" = {
      name = "async";
      packageName = "async";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.0.0.tgz";
        sha1 = "f8fc04ca3a13784ade9e1641af98578cfbd647a9";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.5.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.5.0.tgz";
        sha1 = "c57103f7a17fc037f02d7c2e64b602ea223f7d63";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.8.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.8.0.tgz";
        sha512 = "ReZxvNHIOv88FlT7rxcXIIC0fPt4KZqZbOlivyWtXLt8ESx84zd3kMC6iK5jVeS2qt+g7ftS7ye4fi06X5rtRQ==";
      };
    };
    "babel-runtime-6.26.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz";
        sha1 = "965c7058668e82b55d7bfe04ff2337bc8b5647fe";
      };
    };
    "base64-js-1.3.0" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.0.tgz";
        sha512 = "ccav/yGvoa80BQDljCxsmmQ3Xvx60/UpBIij5QN21W3wBi/hhIC9OoO+KLpu9IJTS9j4DRVJ3aDDF9cMSoa2lw==";
      };
    };
    "basic-auth-1.0.4" = {
      name = "basic-auth";
      packageName = "basic-auth";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/basic-auth/-/basic-auth-1.0.4.tgz";
        sha1 = "030935b01de7c9b94a824b29f3fccb750d3a5290";
      };
    };
    "bcrypt-pbkdf-1.0.2" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz";
        sha1 = "a4301d389b6a43f9b67ff3ca11a3f6637e360e9e";
      };
    };
    "binary-search-tree-0.2.5" = {
      name = "binary-search-tree";
      packageName = "binary-search-tree";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-search-tree/-/binary-search-tree-0.2.5.tgz";
        sha1 = "7dbb3b210fdca082450dad2334c304af39bdc784";
      };
    };
    "bintrees-1.0.1" = {
      name = "bintrees";
      packageName = "bintrees";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bintrees/-/bintrees-1.0.1.tgz";
        sha1 = "0e655c9b9c2435eaab68bf4027226d2b55a34524";
      };
    };
    "bl-0.9.5" = {
      name = "bl";
      packageName = "bl";
      version = "0.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-0.9.5.tgz";
        sha1 = "c06b797af085ea00bc527afc8efcf11de2232054";
      };
    };
    "bluebird-2.11.0" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "2.11.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/bluebird/-/bluebird-2.11.0.tgz";
        sha1 = "534b9033c022c9579c56ba3b3e5a5caafbb650e1";
      };
    };
    "bluebird-3.5.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.5.2.tgz";
        sha512 = "dhHTWMI7kMx5whMQntl7Vr9C6BvV10lFXDAasnqnrMYhXVCzzk6IO9Fo2L75jXHT07WrOngL1WDXOp+yYS91Yg==";
      };
    };
    "body-parser-1.12.4" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.12.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.12.4.tgz";
        sha1 = "090700c4ba28862a8520ef378395fdee5f61c229";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "browser-request-0.3.3" = {
      name = "browser-request";
      packageName = "browser-request";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-request/-/browser-request-0.3.3.tgz";
        sha1 = "9ece5b5aca89a29932242e18bf933def9876cc17";
      };
    };
    "buffer-5.2.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.2.1.tgz";
        sha512 = "c+Ko0loDaFfuPWiL02ls9Xd3GO3cPVmUobQ6t3rXNUk304u6hGq+8N/kFi+QEIKhzK3uwolVhLzszmfLmMLnqg==";
      };
    };
    "bytes-1.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-1.0.0.tgz";
        sha1 = "3569ede8ba34315fab99c3e92cb04c7220de1fa8";
      };
    };
    "bytes-2.1.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-2.1.0.tgz";
        sha1 = "ac93c410e2ffc9cc7cf4b464b38289067f5e47b4";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "caseless-0.9.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.9.0.tgz";
        sha1 = "b7b65ce6bf1413886539cfd533f0b30effa9cf88";
      };
    };
    "chalk-2.4.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.1.tgz";
        sha512 = "ObN6h1v2fTJSmUXoS3nMQ92LbDK9be4TV+6G+omQlGJFdcUX5heKi1LZ1YnRMIgwTLEj3E24bT6tYni50rlCfQ==";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "colors-1.3.2" = {
      name = "colors";
      packageName = "colors";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.3.2.tgz";
        sha512 = "rhP0JSBGYvpcNQj4s5AdShMeE5ahMop96cTeDl/v9qQQm2fYClE2QXZRi8wLzc+GmXSxdIqqbOIAhyObEXDbfQ==";
      };
    };
    "combined-stream-0.0.7" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-0.0.7.tgz";
        sha1 = "0137e657baa5a7541c57ac37ac5fc07d73b4dc1f";
      };
    };
    "combined-stream-1.0.6" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.6.tgz";
        sha1 = "723e7df6e801ac5613113a7e445a9b69cb632818";
      };
    };
    "content-disposition-0.5.0" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.0.tgz";
        sha1 = "4284fe6ae0630874639e44e80a418c2934135e9e";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "cookie-0.1.2" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.1.2.tgz";
        sha1 = "72fec3d24e48a3432073d90c12642005061004b1";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "core-js-2.5.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.5.7.tgz";
        sha512 = "RszJCAxg/PP6uzXVXL6BsxSXx/B05oJAQ2vkJRjyjrEcNVycaqOmNb5OTxZPE3xa5gwZduqza6L9JOCenh/Ecw==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "crc-3.2.1" = {
      name = "crc";
      packageName = "crc";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc/-/crc-3.2.1.tgz";
        sha1 = "5d9c8fb77a245cd5eca291e5d2d005334bab0082";
      };
    };
    "crc-3.8.0" = {
      name = "crc";
      packageName = "crc";
      version = "3.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crc/-/crc-3.8.0.tgz";
        sha512 = "iX3mfgcTMIq3ZKLIsVFAbv7+Mc10kxabAGQb8HvjA1o3T1PIYprbakQ65d3I+2HGHt6nSKkM9PYjgoJO2KcFBQ==";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "ctype-0.5.3" = {
      name = "ctype";
      packageName = "ctype";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ctype/-/ctype-0.5.3.tgz";
        sha1 = "82c18c2461f74114ef16c135224ad0b9144ca12f";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "delayed-stream-0.0.5" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-0.0.5.tgz";
        sha1 = "d4b1f43a93e8296dfe02694f4680bc37a313c73f";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "depd-1.0.1" = {
      name = "depd";
      packageName = "depd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.0.1.tgz";
        sha1 = "80aec64c9d6d97e65cc2a9caa93c0aa6abf73aaa";
      };
    };
    "destroy-1.0.3" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.3.tgz";
        sha1 = "b433b4724e71fd8551d9885174851c5fc377e2c9";
      };
    };
    "dom-serializer-0.1.0" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.1.0.tgz";
        sha1 = "073c697546ce0780ce23be4a28e293e40bc30c82";
      };
    };
    "domelementtype-1.1.3" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.1.3.tgz";
        sha1 = "bd28773e2642881aec51544924299c5cd822185b";
      };
    };
    "domelementtype-1.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.0.tgz";
        sha1 = "b17aed82e8ab59e52dd9c19b1756e0fc187204c2";
      };
    };
    "domhandler-2.4.2" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.4.2.tgz";
        sha512 = "JiK04h0Ht5u/80fdLMCEmV4zkNh2BcoMFBmZ/91WtYZ8qVXSKjiw7fXMgFPnHcSZgOo3XdinHvmnDUeMf5R4wA==";
      };
    };
    "domutils-1.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.7.0.tgz";
        sha512 = "Lgd2XcJ/NjEw+7tFvfKxOzCYKZsdct5lczQ2ZaQY8Djz7pfAD3Gbp8ySJWtreII/vDlMVmxwa6pHmdxIYgttDg==";
      };
    };
    "ecc-jsbn-0.1.2" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.2.tgz";
        sha1 = "3a83a904e54353287874c564b7549386849a98c9";
      };
    };
    "ee-first-1.1.0" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.0.tgz";
        sha1 = "6a0d7c6221e490feefd92ec3f441c9ce8cd097f4";
      };
    };
    "entities-1.1.1" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.1.tgz";
        sha1 = "6e5c2d0a5621b5dadaecef80b90edfb5cd7772f0";
      };
    };
    "escape-html-1.0.1" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.1.tgz";
        sha1 = "181a286ead397a39a92857cfb1d43052e356bff0";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "etag-1.6.0" = {
      name = "etag";
      packageName = "etag";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.6.0.tgz";
        sha1 = "8bcb2c6af1254c481dfc8b997c906ef4e442c207";
      };
    };
    "express-4.12.4" = {
      name = "express";
      packageName = "express";
      version = "4.12.4";
      src = fetchurl {
        url = "http://registry.npmjs.org/express/-/express-4.12.4.tgz";
        sha1 = "8fec2510255bc6b2e58107c48239c0fa307c1aa2";
      };
    };
    "extend-2.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-2.0.2.tgz";
        sha512 = "AgFD4VU+lVLP6vjnlNfF7OeInLTyeyckCNPEsuxz1vi786UuK/nk6ynPuhn/h+Ju9++TQyr5EpLRI14fc1QtTQ==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "fast-deep-equal-1.1.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.1.0.tgz";
        sha1 = "c053477817c86b51daa853c81e059b733d023614";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "fast-safe-stringify-2.0.6" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.0.6.tgz";
        sha512 = "q8BZ89jjc+mz08rSxROs8VsrBBcn1SIw1kq9NjolL509tkABRk9io01RAjSaEv1Xb2uFLt8VtRiZbGp5H8iDtg==";
      };
    };
    "fecha-2.3.3" = {
      name = "fecha";
      packageName = "fecha";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fecha/-/fecha-2.3.3.tgz";
        sha512 = "lUGBnIamTAwk4znq5BcqsDaxSmZ9nDVJaij6NvRt/Tg4R69gERA+otPKbS86ROw9nxVMw2/mp1fnaiWqbs6Sdg==";
      };
    };
    "file-stream-rotator-0.3.1" = {
      name = "file-stream-rotator";
      packageName = "file-stream-rotator";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-stream-rotator/-/file-stream-rotator-0.3.1.tgz";
        sha512 = "Vr6M5qmomoyJyjGEpvMJd74HWXe/6D1eB342QwJpb0WenGaBhe3IhzJQWzcKIEq5O3yYum45r4lYsQAm7cO1yA==";
      };
    };
    "finalhandler-0.3.6" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-0.3.6.tgz";
        sha1 = "daf9c4161b1b06e001466b1411dfdb6973be138b";
      };
    };
    "forever-agent-0.5.2" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.5.2.tgz";
        sha1 = "6d0e09c4921f94a27f63d3b49c5feff1ea4c5130";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-0.2.0" = {
      name = "form-data";
      packageName = "form-data";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-0.2.0.tgz";
        sha1 = "26f8bc26da6440e299cbdcfb69035c4f77a6e466";
      };
    };
    "form-data-2.3.2" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.2.tgz";
        sha1 = "4970498be604c20c005d4f5c23aecd21d6b49099";
      };
    };
    "forwarded-0.1.2" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.2.tgz";
        sha1 = "98c23dab1175657b8c0573e8ceccd91b0ff18c84";
      };
    };
    "fresh-0.2.4" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.2.4.tgz";
        sha1 = "3582499206c9723714190edd74b4604feb4a614c";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.1.0" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.1.0.tgz";
        sha512 = "+qnmNjI4OfH2ipQ9VQOw23bBd/ibtfbVdK2fYbY4acTDqKTW/YDp9McimZdDbG8iV9fZizUqQMD5xvriB146TA==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "hawk-2.3.1" = {
      name = "hawk";
      packageName = "hawk";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-2.3.1.tgz";
        sha1 = "1e731ce39447fa1d0f6d707f7bceebec0fd1ec1f";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "htmlparser2-3.9.2" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.9.2.tgz";
        sha1 = "1bdf87acca0f3f9e53fa4fcceb0f4b4cbb00b338";
      };
    };
    "http-signature-0.10.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "0.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-0.10.1.tgz";
        sha1 = "4fbdac132559aa8323121e540779c0a012b27e66";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "iconv-lite-0.4.8" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.8.tgz";
        sha1 = "c6019a7595f2cefca702eab694a010bcd9298d20";
      };
    };
    "ieee754-1.1.12" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.12.tgz";
        sha512 = "GguP+DRY+pJ3soyIiGPTvdiVXjZ+DbXOxGpXn3eMvNW4x4irjqXm4wHKscC+TfxSJ0yw/S1F24tqdMNsMZTiLA==";
      };
    };
    "immediate-3.0.6" = {
      name = "immediate";
      packageName = "immediate";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/immediate/-/immediate-3.0.6.tgz";
        sha1 = "9db1dbd0faf8de6fbe0f5dd5e56bb606280de69b";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "ipaddr.js-1.0.5" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.0.5.tgz";
        sha1 = "5fa78cf301b825c78abc3042d812723049ea23c7";
      };
    };
    "irc-colors-1.4.3" = {
      name = "irc-colors";
      packageName = "irc-colors";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/irc-colors/-/irc-colors-1.4.3.tgz";
        sha512 = "VeAnFC9fkb4nB/s6UtTNf3BH2wOk/sSBSzIzCpFwrgoFxVl6J5sov7FXXA0kmbk/mVAZQXfXAsQFjWnGPf4cRg==";
      };
    };
    "irc-git://github.com/matrix-org/node-irc#c9abb427bec5016d94a2abf3e058cc62de09ea5a" = {
      name = "irc";
      packageName = "irc";
      version = "0.3.12";
      src = fetchgit {
        url = "git://github.com/matrix-org/node-irc";
        rev = "c9abb427bec5016d94a2abf3e058cc62de09ea5a";
        sha256 = "c349f40307b38c1127c6a49c8137b2160e991431b497ed106e9e7b144bdd4362";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jayschema-0.3.2" = {
      name = "jayschema";
      packageName = "jayschema";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jayschema/-/jayschema-0.3.2.tgz";
        sha512 = "UHLk2ya7ItaLjmMVJWGE9b5t7jD3DZfmURdmz+rOVSiSYnrCtgcxvNXuQavcK7bhUBlXFmrXwRAPXkCMDxxANg==";
      };
    };
    "js-yaml-3.12.0" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.12.0.tgz";
        sha512 = "PIt2cnwmPfL4hKNwqeiuz4bKfnzHTBv6HyVgjahA6mPLwPDzjDWrplJBMjHUFxku/N3FlmrbyPclad+I+4mJ3A==";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "lie-3.1.1" = {
      name = "lie";
      packageName = "lie";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lie/-/lie-3.1.1.tgz";
        sha1 = "9a436b2cc7746ca59de7a41fa469b3efb76bd87e";
      };
    };
    "localforage-1.7.2" = {
      name = "localforage";
      packageName = "localforage";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/localforage/-/localforage-1.7.2.tgz";
        sha1 = "fa4442602f806edd2bca6a54ab4e656f031f121c";
      };
    };
    "lodash.clonedeep-4.5.0" = {
      name = "lodash.clonedeep";
      packageName = "lodash.clonedeep";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz";
        sha1 = "e23f3f9c4f8fbdde872529c1071857a086e5ccef";
      };
    };
    "lodash.escaperegexp-4.1.2" = {
      name = "lodash.escaperegexp";
      packageName = "lodash.escaperegexp";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.escaperegexp/-/lodash.escaperegexp-4.1.2.tgz";
        sha1 = "64762c48618082518ac3df4ccf5d5886dae20347";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "lodash.isstring-4.0.1" = {
      name = "lodash.isstring";
      packageName = "lodash.isstring";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isstring/-/lodash.isstring-4.0.1.tgz";
        sha1 = "d527dfb5456eca7cc9bb95d5daeaf88ba54a5451";
      };
    };
    "lodash.mergewith-4.6.1" = {
      name = "lodash.mergewith";
      packageName = "lodash.mergewith";
      version = "4.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.mergewith/-/lodash.mergewith-4.6.1.tgz";
        sha512 = "eWw5r+PYICtEBgrBE5hhlT6aAa75f411bgDz/ZL2KZqYV03USvucsxcHUIlGTDTECs1eunpI7HOV7U+WLDvNdQ==";
      };
    };
    "logform-1.9.1" = {
      name = "logform";
      packageName = "logform";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/logform/-/logform-1.9.1.tgz";
        sha512 = "ZHrZE8VSf7K3xKxJiQ1aoTBp2yK+cEbFcgarsjzI3nt3nE/3O0heNSppoOQMUJVMZo/xiVwCxiXIabaZApsKNQ==";
      };
    };
    "matrix-appservice-0.3.4" = {
      name = "matrix-appservice";
      packageName = "matrix-appservice";
      version = "0.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-appservice/-/matrix-appservice-0.3.4.tgz";
        sha1 = "33869bdcf315274b94254cc39d965d63c9cb1323";
      };
    };
    "matrix-appservice-bridge-1.6.1" = {
      name = "matrix-appservice-bridge";
      packageName = "matrix-appservice-bridge";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-appservice-bridge/-/matrix-appservice-bridge-1.6.1.tgz";
        sha512 = "jYg3BF9iuGTexYjWGfOJsf1OC7k2ECgSONnHLL6hZR3q5Vr8nEy7aw2JG+4h6jjOQ8enx1VSur2+Nj5S35ybCA==";
      };
    };
    "matrix-js-sdk-0.10.9" = {
      name = "matrix-js-sdk";
      packageName = "matrix-js-sdk";
      version = "0.10.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/matrix-js-sdk/-/matrix-js-sdk-0.10.9.tgz";
        sha512 = "2d8dziVXh/jO48a+ju16Qn90QHgx3MLSK//Kx1GF/5jL80xrw1Pq4ijgcypt0ntG0vQ0ALfzQ27hse/KO6QVDw==";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "merge-descriptors-1.0.0" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.0.tgz";
        sha1 = "2169cf7538e1b0cc87fb88e1502d8474bbf79864";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "mime-db-1.12.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.12.0.tgz";
        sha1 = "3d0c63180f458eb10d325aaa37d7c58ae312e9d7";
      };
    };
    "mime-db-1.36.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.36.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.36.0.tgz";
        sha512 = "L+xvyD9MkoYMXb1jAmzI/lWYAxAMCPvIBSWur0PZ5nOf5euahRLVqH//FKW9mWp2lkqUgYiXPgkzfMUFi4zVDw==";
      };
    };
    "mime-types-2.0.14" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.0.14.tgz";
        sha1 = "310e159db23e077f8bb22b748dabfa4957140aa6";
      };
    };
    "mime-types-2.1.20" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.20.tgz";
        sha512 = "HrkrPaP9vGuWbLK1B1FfgAkbqNjIuy4eHlIYnFi7kamZyLLrGlo2mpcx0bBmNpKqBtYtAfGbodDddIgddSJC2A==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "http://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "http://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "moment-2.22.2" = {
      name = "moment";
      packageName = "moment";
      version = "2.22.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.22.2.tgz";
        sha1 = "3c257f9839fc0e93ff53149632239eb90783ff66";
      };
    };
    "morgan-1.5.3" = {
      name = "morgan";
      packageName = "morgan";
      version = "1.5.3";
      src = fetchurl {
        url = "http://registry.npmjs.org/morgan/-/morgan-1.5.3.tgz";
        sha1 = "8adb4e72f9e5c5436e5d93f42910835f79da9fdf";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "ms-2.1.1" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz";
        sha512 = "tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==";
      };
    };
    "nedb-1.8.0" = {
      name = "nedb";
      packageName = "nedb";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nedb/-/nedb-1.8.0.tgz";
        sha1 = "0e3502cd82c004d5355a43c9e55577bd7bd91d88";
      };
    };
    "negotiator-0.5.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.5.3.tgz";
        sha1 = "269d5c476810ec92edbe7b6c2f28316384f9a7e8";
      };
    };
    "node-uuid-1.4.8" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.8.tgz";
        sha1 = "b040eb0923968afabf8d32fb1f17f1167fdab907";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "oauth-sign-0.6.0" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.6.0.tgz";
        sha1 = "7dbeae44f6ca454e1f168451d630746735813ce3";
      };
    };
    "oauth-sign-0.9.0" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.9.0.tgz";
        sha512 = "fexhUFFPTGV8ybAtSIGbV6gOkSv8UtRbDBnAyLQw4QPKkgNlsH2ByPGtMUqdWkos6YCRmAqViwgZrJc/mRDzZQ==";
      };
    };
    "on-finished-2.2.1" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.2.1.tgz";
        sha1 = "5c85c1cc36299f78029653f667f27b6b99ebc029";
      };
    };
    "parseurl-1.3.2" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz";
        sha1 = "fc289d4ed8993119460c156253262cdc8de65bf3";
      };
    };
    "path-to-regexp-0.1.3" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.3.tgz";
        sha1 = "21b9ab82274279de25b156ea08fd12ca51b8aecb";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "postcss-6.0.23" = {
      name = "postcss";
      packageName = "postcss";
      version = "6.0.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-6.0.23.tgz";
        sha512 = "soOk1h6J3VMTZtVeVpv15/Hpdl2cBLX3CAw4TAbkpTJiNPk9YP/zWcD1ND+xEtvyuuvKzbxliTOIyvkSeSJ6ag==";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
      };
    };
    "prom-client-11.1.1" = {
      name = "prom-client";
      packageName = "prom-client";
      version = "11.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prom-client/-/prom-client-11.1.1.tgz";
        sha512 = "itUicyrq3Rko56v3ovQAMYwxEouK7lIylp26bjnlt1b/3fzn783riZnZn432I4udYmPsRgNx1F/u9RFvLyH7zA==";
      };
    };
    "prom-client-6.3.0" = {
      name = "prom-client";
      packageName = "prom-client";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prom-client/-/prom-client-6.3.0.tgz";
        sha1 = "5826993809ac554156e168cb44f218777cd0d4de";
      };
    };
    "proxy-addr-1.0.10" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.0.10.tgz";
        sha1 = "0d40a82f801fc355567d2ecb65efe3f077f121c5";
      };
    };
    "psl-1.1.29" = {
      name = "psl";
      packageName = "psl";
      version = "1.1.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/psl/-/psl-1.1.29.tgz";
        sha512 = "AeUmQ0oLN02flVHXWh9sSJF7mcdFq0ppid/JkErufc3hGIV/AMa8Fo9VgDo/cT2jFdOWoFvHp90qqBH54W+gjQ==";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "qs-2.3.3" = {
      name = "qs";
      packageName = "qs";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-2.3.3.tgz";
        sha1 = "e9e85adbe75da0bbe4c8e0476a086290f863b404";
      };
    };
    "qs-2.4.2" = {
      name = "qs";
      packageName = "qs";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-2.4.2.tgz";
        sha1 = "f7ce788e5777df0b5010da7f7c4e73ba32470f5a";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "N5ZAX4/LxJmF+7wN74pUD6qAh9/wnvdQcjq9TZjevvXzSUo7bfmw91saqMjzGS2xq91/odN2dW/WOl7qQHNDGA==";
      };
    };
    "range-parser-1.0.3" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.0.3.tgz";
        sha1 = "6872823535c692e2c2a0103826afd82c2e0ff175";
      };
    };
    "raw-body-2.0.2" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.0.2.tgz";
        sha1 = "a2c2f98c8531cee99c63d8d238b7de97bb659fca";
      };
    };
    "readable-stream-1.0.34" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.34";
      src = fetchurl {
        url = "http://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz";
        sha1 = "125820e34bc842d2f2aaafafe4c2916ee32c157c";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "http://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "regenerator-runtime-0.11.1" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.1.tgz";
        sha512 = "MguG95oij0fC3QV3URf4V2SDYGJhJnJGqvIIgdECeODCT98wSWDAJ94SSuVpYQUoTcGUIL6L4yNB7j1DFFHSBg==";
      };
    };
    "request-2.53.0" = {
      name = "request";
      packageName = "request";
      version = "2.53.0";
      src = fetchurl {
        url = "http://registry.npmjs.org/request/-/request-2.53.0.tgz";
        sha1 = "180a3ae92b7b639802e4f9545dd8fcdeb71d760c";
      };
    };
    "request-2.88.0" = {
      name = "request";
      packageName = "request";
      version = "2.88.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.88.0.tgz";
        sha512 = "NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E+lHDAJzu7kLAkDeY08z2/A0hg==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sanitize-html-1.18.5" = {
      name = "sanitize-html";
      packageName = "sanitize-html";
      version = "1.18.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanitize-html/-/sanitize-html-1.18.5.tgz";
        sha512 = "z0MV+AqOnDZVSQQHr/vwimRykKVyPuGZnjWDzIiV1mdgQEG9HMx9qrEapcOQeUmSsPvHZ04BXTuXQkB/vvbU9A==";
      };
    };
    "semver-5.5.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.5.1.tgz";
        sha512 = "PqpAxfrEhlSUWge8dwIp4tZnQ25DIOthpiaHNIthsjEFQD6EvqUKUDM7L8O2rShkFccYo1VjJR0coWfNkCubRw==";
      };
    };
    "send-0.12.3" = {
      name = "send";
      packageName = "send";
      version = "0.12.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.12.3.tgz";
        sha1 = "cd12dc58fde21e4f91902b39b2fda05a7a6d9bdc";
      };
    };
    "serve-static-1.9.3" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.9.3.tgz";
        sha1 = "5f8da07323ad385ff3dc541f1a7917b2e436eb57";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "srcset-1.0.0" = {
      name = "srcset";
      packageName = "srcset";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/srcset/-/srcset-1.0.0.tgz";
        sha1 = "a5669de12b42f3b1d5e83ed03c71046fc48f41ef";
      };
    };
    "sshpk-1.14.2" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.14.2.tgz";
        sha1 = "c6fc61648a3d9c4e764fd3fcdf4ea105e492ba98";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "stringstream-0.0.6" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.6.tgz";
        sha512 = "87GEBAkegbBcweToUrdzf3eLhWNg06FJTebl4BVJz/JgWy8CvEr9dRtX5qWphiynMSQlxxi+QqN0z5T32SLlhA==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "tdigest-0.1.1" = {
      name = "tdigest";
      packageName = "tdigest";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tdigest/-/tdigest-0.1.1.tgz";
        sha1 = "2e3cb2c39ea449e55d1e6cd91117accca4588021";
      };
    };
    "tough-cookie-2.4.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.4.3.tgz";
        sha512 = "Q5srk/4vDM54WJsJio3XNn6K2sCG+CQ8G5Wz6bZhRZoAe/+TxjWB/GlFAnYEbkYVlON9FMk/fE3h2RLpPXo4lQ==";
      };
    };
    "triple-beam-1.3.0" = {
      name = "triple-beam";
      packageName = "triple-beam";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/triple-beam/-/triple-beam-1.3.0.tgz";
        sha512 = "XrHUvV5HpdLmIj4uVMxHggLbFSZYIn7HEWsqePZcI50pco+MPqJ50wMGY794X7AOOhxOBAjbkqfAbEe/QMp2Lw==";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "type-is-1.6.16" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.16.tgz";
        sha512 = "HRkVv/5qY2G6I8iab9cI7v1bOIdhm94dVjQCPFElW9W+3GeDOSHmy2EBYe4VTApuzolPcmgFTN3ftVJRKR2J9Q==";
      };
    };
    "underscore-1.4.4" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz";
        sha1 = "61a6a32010622afa07963bf325203cf12239d604";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "util-extend-1.0.3" = {
      name = "util-extend";
      packageName = "util-extend";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-extend/-/util-extend-1.0.3.tgz";
        sha1 = "a7c216d267545169637b3b6edc6ca9119e2ff93f";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "uuid-3.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.2.tgz";
        sha512 = "yXJmeNaw3DnnKAOKJE51sL/ZaYfWJRl1pK9dr19YFCu0ObS231AB1/LbqTKRAQ5kw8A90rA6fr4riOUpTZvQZA==";
      };
    };
    "vary-1.0.1" = {
      name = "vary";
      packageName = "vary";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.0.1.tgz";
        sha1 = "99e4981566a286118dfb2b817357df7993376d10";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "when-3.4.6" = {
      name = "when";
      packageName = "when";
      version = "3.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/when/-/when-3.4.6.tgz";
        sha1 = "8fbcb7cc1439d2c3a68c431f1516e6dcce9ad28c";
      };
    };
    "winston-2.4.4" = {
      name = "winston";
      packageName = "winston";
      version = "2.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-2.4.4.tgz";
        sha512 = "NBo2Pepn4hK4V01UfcWcDlmiVTs7VTB1h7bgnB0rgP146bYhMxX0ypCz3lBOfNxCO4Zuek7yeT+y/zM1OfMw4Q==";
      };
    };
    "winston-compat-0.1.4" = {
      name = "winston-compat";
      packageName = "winston-compat";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-compat/-/winston-compat-0.1.4.tgz";
        sha512 = "mMEfFsSm6GmkFF+f4/0UJtG4N1vSaczGmXLVJYmS/+u2zUaIPcw2ZRuwUg2TvVBjswgiraN+vNnAG8z4fRUZ4w==";
      };
    };
    "winston-daily-rotate-file-3.3.2" = {
      name = "winston-daily-rotate-file";
      packageName = "winston-daily-rotate-file";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-daily-rotate-file/-/winston-daily-rotate-file-3.3.2.tgz";
        sha512 = "JTR5aZttsdZcKuAD6JAs9fIpaHC71ZjutsnqvIXumoGPT1waAo8qyFzmQpljJ2Yqsslh6xy0PyyEGKC+C4Bvzg==";
      };
    };
    "winston-transport-4.2.0" = {
      name = "winston-transport";
      packageName = "winston-transport";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-transport/-/winston-transport-4.2.0.tgz";
        sha512 = "0R1bvFqxSlK/ZKTH86nymOuKv/cT1PQBMuDdA7k7f0S9fM44dNH6bXnuxwXPrN8lefJgtZq08BKdyZ0DZIy/rg==";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
  };
in
{
  "matrix-appservice-irc-0.11.1" = nodeEnv.buildNodePackage {
    name = "matrix-appservice-irc";
    packageName = "matrix-appservice-irc";
    version = "0.11.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/matrix-appservice-irc/-/matrix-appservice-irc-0.11.1.tgz";
      sha512 = "usxZT5MQ/pzLzcacML3DifVWqfDaIKHVNHiltSHw3nO9Hq/SQZxtWc97YLUmsNDZyvvOsrqmZP6SRVSFocpEhA==";
    };
    dependencies = [
      sources."abbrev-1.1.1"
      sources."accepts-1.2.13"
      sources."ajv-5.5.2"
      sources."another-json-0.2.0"
      sources."ansi-styles-3.2.1"
      sources."argparse-1.0.10"
      sources."array-uniq-1.0.3"
      sources."asn1-0.1.11"
      sources."assert-plus-0.1.5"
      sources."async-0.9.2"
      sources."asynckit-0.4.0"
      sources."aws-sign2-0.5.0"
      sources."aws4-1.8.0"
      sources."babel-runtime-6.26.0"
      sources."base64-js-1.3.0"
      sources."basic-auth-1.0.4"
      sources."bcrypt-pbkdf-1.0.2"
      sources."binary-search-tree-0.2.5"
      sources."bintrees-1.0.1"
      sources."bl-0.9.5"
      sources."bluebird-3.5.2"
      sources."body-parser-1.12.4"
      sources."boom-2.10.1"
      sources."browser-request-0.3.3"
      sources."buffer-5.2.1"
      sources."bytes-1.0.0"
      sources."caseless-0.9.0"
      sources."chalk-2.4.1"
      sources."co-4.6.0"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."colors-1.0.3"
      sources."combined-stream-0.0.7"
      sources."content-disposition-0.5.0"
      sources."content-type-1.0.4"
      sources."cookie-0.1.2"
      sources."cookie-signature-1.0.6"
      sources."core-js-2.5.7"
      sources."core-util-is-1.0.2"
      sources."crc-3.8.0"
      sources."cryptiles-2.0.5"
      sources."ctype-0.5.3"
      sources."cycle-1.0.3"
      (sources."dashdash-1.14.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."debug-2.2.0"
      sources."delayed-stream-0.0.5"
      sources."depd-1.0.1"
      sources."destroy-1.0.3"
      (sources."dom-serializer-0.1.0" // {
        dependencies = [
          sources."domelementtype-1.1.3"
        ];
      })
      sources."domelementtype-1.3.0"
      sources."domhandler-2.4.2"
      sources."domutils-1.7.0"
      sources."ecc-jsbn-0.1.2"
      sources."ee-first-1.1.0"
      sources."entities-1.1.1"
      sources."escape-html-1.0.1"
      sources."escape-string-regexp-1.0.5"
      sources."esprima-4.0.1"
      (sources."etag-1.6.0" // {
        dependencies = [
          sources."crc-3.2.1"
        ];
      })
      sources."express-4.12.4"
      sources."extend-2.0.2"
      sources."extsprintf-1.3.0"
      sources."eyes-0.1.8"
      sources."fast-deep-equal-1.1.0"
      sources."fast-json-stable-stringify-2.0.0"
      sources."fast-safe-stringify-2.0.6"
      sources."fecha-2.3.3"
      sources."file-stream-rotator-0.3.1"
      sources."finalhandler-0.3.6"
      sources."forever-agent-0.5.2"
      (sources."form-data-0.2.0" // {
        dependencies = [
          sources."mime-db-1.12.0"
          sources."mime-types-2.0.14"
        ];
      })
      sources."forwarded-0.1.2"
      sources."fresh-0.2.4"
      (sources."getpass-0.1.7" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."har-schema-2.0.0"
      sources."har-validator-5.1.0"
      sources."has-flag-3.0.0"
      sources."hawk-2.3.1"
      sources."hoek-2.16.3"
      (sources."htmlparser2-3.9.2" // {
        dependencies = [
          sources."isarray-1.0.0"
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."http-signature-0.10.1"
      sources."iconv-lite-0.4.8"
      sources."ieee754-1.1.12"
      sources."immediate-3.0.6"
      sources."inherits-2.0.3"
      sources."ipaddr.js-1.0.5"
      sources."irc-git://github.com/matrix-org/node-irc#c9abb427bec5016d94a2abf3e058cc62de09ea5a"
      sources."irc-colors-1.4.3"
      sources."is-typedarray-1.0.0"
      sources."isarray-0.0.1"
      sources."isstream-0.1.2"
      sources."jayschema-0.3.2"
      sources."js-yaml-3.12.0"
      sources."jsbn-0.1.1"
      sources."json-schema-0.2.3"
      sources."json-schema-traverse-0.3.1"
      sources."json-stringify-safe-5.0.1"
      (sources."jsprim-1.4.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."lie-3.1.1"
      sources."localforage-1.7.2"
      sources."lodash.clonedeep-4.5.0"
      sources."lodash.escaperegexp-4.1.2"
      sources."lodash.isplainobject-4.0.6"
      sources."lodash.isstring-4.0.1"
      sources."lodash.mergewith-4.6.1"
      (sources."logform-1.9.1" // {
        dependencies = [
          sources."colors-1.3.2"
          sources."ms-2.1.1"
        ];
      })
      (sources."matrix-appservice-0.3.4" // {
        dependencies = [
          sources."mime-db-1.12.0"
          sources."mime-types-2.0.14"
          sources."qs-2.3.3"
          sources."request-2.53.0"
        ];
      })
      (sources."matrix-appservice-bridge-1.6.1" // {
        dependencies = [
          sources."bluebird-2.11.0"
          sources."extend-3.0.2"
          sources."prom-client-11.1.1"
        ];
      })
      sources."matrix-js-sdk-0.10.9"
      sources."media-typer-0.3.0"
      sources."merge-descriptors-1.0.0"
      sources."methods-1.1.2"
      sources."mime-1.3.4"
      sources."mime-db-1.36.0"
      sources."mime-types-2.1.20"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."moment-2.22.2"
      sources."morgan-1.5.3"
      sources."ms-0.7.1"
      (sources."nedb-1.8.0" // {
        dependencies = [
          sources."async-0.2.10"
        ];
      })
      sources."negotiator-0.5.3"
      sources."node-uuid-1.4.8"
      sources."nopt-3.0.6"
      sources."number-is-nan-1.0.1"
      sources."oauth-sign-0.6.0"
      sources."on-finished-2.2.1"
      sources."parseurl-1.3.2"
      sources."path-to-regexp-0.1.3"
      sources."performance-now-2.1.0"
      sources."postcss-6.0.23"
      sources."process-nextick-args-2.0.0"
      sources."prom-client-6.3.0"
      sources."proxy-addr-1.0.10"
      sources."psl-1.1.29"
      sources."punycode-1.4.1"
      sources."qs-2.4.2"
      sources."range-parser-1.0.3"
      (sources."raw-body-2.0.2" // {
        dependencies = [
          sources."bytes-2.1.0"
        ];
      })
      sources."readable-stream-1.0.34"
      sources."regenerator-runtime-0.11.1"
      (sources."request-2.88.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
          sources."aws-sign2-0.7.0"
          sources."caseless-0.12.0"
          sources."combined-stream-1.0.6"
          sources."delayed-stream-1.0.0"
          sources."extend-3.0.2"
          sources."forever-agent-0.6.1"
          sources."form-data-2.3.2"
          sources."http-signature-1.2.0"
          sources."oauth-sign-0.9.0"
          sources."qs-6.5.2"
          sources."tunnel-agent-0.6.0"
        ];
      })
      sources."safe-buffer-5.1.2"
      sources."safer-buffer-2.1.2"
      sources."sanitize-html-1.18.5"
      sources."semver-5.5.1"
      sources."send-0.12.3"
      sources."serve-static-1.9.3"
      sources."sntp-1.0.9"
      sources."source-map-0.6.1"
      sources."sprintf-js-1.0.3"
      sources."srcset-1.0.0"
      (sources."sshpk-1.14.2" // {
        dependencies = [
          sources."asn1-0.2.4"
          sources."assert-plus-1.0.0"
        ];
      })
      sources."stack-trace-0.0.10"
      sources."string_decoder-0.10.31"
      sources."stringstream-0.0.6"
      sources."supports-color-5.5.0"
      sources."tdigest-0.1.1"
      sources."tough-cookie-2.4.3"
      sources."triple-beam-1.3.0"
      sources."tunnel-agent-0.4.3"
      sources."tweetnacl-0.14.5"
      sources."type-is-1.6.16"
      sources."underscore-1.4.4"
      sources."util-deprecate-1.0.2"
      sources."util-extend-1.0.3"
      sources."utils-merge-1.0.0"
      sources."uuid-3.3.2"
      sources."vary-1.0.1"
      (sources."verror-1.10.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."when-3.4.6"
      (sources."winston-2.4.4" // {
        dependencies = [
          sources."async-1.0.0"
        ];
      })
      sources."winston-compat-0.1.4"
      sources."winston-daily-rotate-file-3.3.2"
      (sources."winston-transport-4.2.0" // {
        dependencies = [
          sources."isarray-1.0.0"
          sources."readable-stream-2.3.6"
          sources."string_decoder-1.1.1"
        ];
      })
      sources."xtend-4.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An IRC Bridge for Matrix";
      homepage = "https://github.com/matrix-org/matrix-appservice-irc#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
  };
}